---
title: "在R Markdown文档中使用中文"
author:
  - 刘涛

documentclass: ctexart
keywords:
  - 中文
  - R Markdown
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("limma")
```
# 切换文件地址

```{r}
setwd("C:/Users/刘涛/Desktop/SIT/GSE137537")
###读取mtx稀疏矩阵
mt <- Matrix::readMM("counts.mtx")
dim(mt)# 行为基因，列为细胞

###读取txt文件基因名，作为稀疏矩阵行名
gene_names<- read.table('gene_names.txt')
row.names(mt) <- gene_names[,1]

###读取tsv文件
cell <- read.table("annotations.tsv",header = T)
colnames(mt) <- cell$Barcode
```
```{r}
MR2<-cell$scater_qc.all.log10_total_features_by_counts[cell$tissue=="PR2"]
# 加载 ggplot2 库
library(ggplot2)

# 创建数据框
data <- data.frame(MR2)

# 绘制直方图
ggplot(data, aes(x = MR2)) +
  geom_histogram(binwidth = 0.01, fill = "skyblue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of MR2",
       x = "MR2 values",
       y = "Frequency")
```

```{r}
# 加载 dplyr 库
library(dplyr)
# 使用 mutate() 函数新增一列 PR_or_MR，根据 tissue 列的内容进行赋值
cell <- cell %>%
  mutate(PR_or_MR = ifelse(grepl("PR", tissue), "No", ifelse(grepl("MR", tissue), "Yes", "Other")))

```

```{r}
wilcox.test(cell$scater_qc.all.total_features_by_counts[cell$PR_or_MR=="Yes"],
            cell$scater_qc.all.total_features_by_counts[cell$individual=="No"])
```

```{r}
install.packages("rcompanion")
```
```{r}
library(rcompanion)
scheirerRayHare(scater_qc.all.total_features_by_counts~PR_or_MR+individual,data = cell)
```

```{r}
csv_file <- "C:/Users/刘涛/Desktop/SIT/GSE137537/cell.csv"
write.csv(cell, file = csv_file, row.names = F)
```

```{r}
# 导入所需的包
library(Matrix)
# 将 Matrix 对象转换为数据框
mt_df <- as.data.frame(as.matrix(t(new_mt)))

# 定义 CSV 文件路径
csv_file <-"C:/Users/刘涛/Desktop/SIT/GSE137537/goal_gene_mt.csv"

# 将数据写入 CSV 文件
write.csv(mt_df, file = csv_file, row.names = T)
```

```{r}
save(goal_gene_mt, file = "C:/Users/刘涛/Desktop/SIT/GSE137537/goal_gene_mt.RData")
```
# 差异化分析
1.导入所需要的包
```{r}
library(limma)
library(magrittr)
```
2.加载数据
```{r}
head(mt)
```
3.样本信息注释
```{r}
list <- c(rep("MR", 5121), rep("PR",4137),rep("PR",3444),rep("MR",3119),rep("PR",2505),rep("MR",1765)) %>% factor(., levels = c("PR", "MR"), ordered = F)
head(list)
list <- model.matrix(~factor(list)+0)  #把group设置成一个model matrix
colnames(list) <- c("CK", "Treat")
```
```{r}
df.fit <- lmFit(mt, list)  ## 数据与list进行匹配
```
4.差异分析
```{r}
df.matrix <- makeContrasts(Treat - CK , levels = list)
fit <- contrasts.fit(df.fit, df.matrix)
fit <- eBayes(fit)
tempOutput <- topTable(fit,n = Inf, adjust = "fdr",lfc = F)
```

```{r}
head(tempOutput)
```
5.导出差异结果
```{r}
## 导出所有的差异结果
nrDEG = na.omit(tempOutput) ## 去掉数据中有NA的行或列
diffsig <- nrDEG 
head(diffsig)
```
6.筛选差异基因
这里一般用p值小于0.05来筛选
```{r}
padj = 0.05
foldChange = 0.5
# 筛选出所有差异基因的结果
All_diffSig <- diffsig[(diffsig$P.Value < padj&abs(diffsig$logFC)>foldChange),]
#采用未修正的p值进行筛选
write.csv(All_diffSig, "C:/Users/刘涛/Desktop/SIT/GSE137537/all.diffsig.csv")  ##输出差异基因数据集
```
7.筛选上调和下调的基因
```{r}
diffup <-  All_diffSig[(All_diffSig$P.Value < padj & (All_diffSig$logFC > foldChange)),]
write.csv(diffup, "diffup.csv")
#
diffdown <- All_diffSig[(All_diffSig$P.Value < padj & (All_diffSig < -foldChange)),]
write.csv(diffdown, "diffdown.csv")
```
8.绘制火山图
```{r}
## 导入R包
library(ggplot2)
library(ggrepel)
##  绘制火山图
## 进行分类别
logFC <- diffsig$log2FC
deg.padj <- diffsig$P.Value
data <- data.frame(logFC = logFC, padj = deg.padj)
data$group[(data$padj > 0.05 | data$padj == "NA") | (data$logFC < foldChange) & data$logFC > -foldChange] <- "Not"
data$group[(data$padj <= 0.05 & data$logFC > 1)] <-  "Up"
data$group[(data$padj <= 0.05 & data$logFC < -1)] <- "Down"
x_lim <- max(logFC,-logFC)

# 开始绘图
pdf('C:/Users/刘涛/Desktop/SIT/GSE137537/volcano.pdf',width = 7,height = 6.5)  ## 输出文件
label = subset(diffsig,P.Value <0.05 & abs(logFC) > 0.5)
label1 = rownames(label)

colnames(diffsig)[2] = 'log2FC'
Significant=ifelse((diffsig$P.Value < 0.05 & abs(diffsig$log2FC)> 0.5), ifelse(diffsig$log2FC > 0.5,"Up","Down"), "Not")

ggplot(diffsig, aes(log2FC, -log10(P.Value)))+
  geom_point(aes(col=Significant))+
  scale_color_manual(values=c("#0072B5","grey","#BC3C28"))+
  labs(title = " ")+
  geom_vline(xintercept=c(-0.5,0.5), colour="black", linetype="dashed")+
  geom_hline(yintercept = -log10(0.05),colour="black", linetype="dashed")+
  theme(plot.title = element_text(size = 16, hjust = 0.5, face = "bold"))+
  labs(x="log2(FoldChange)",y="-log10(Pvalue)")+
  theme(axis.text=element_text(size=13),axis.title=element_text(size=13))+theme_bw()

dev.off()
```
#基因调控网络构建
1.筛选目标基因
```{r}
diff_genes_row <- row.names(diffsig[diffsig$P.Value < padj & abs(diffsig$logFC) > foldChange,])
diff_genes_row
goal_gene<-diffsig[diff_genes_row,"ID"]
goal_gene_mt<-mt[goal_gene,]
row.names(goal_gene_mt)
```
2.移除标记基因中零比例大于50%的细胞
```{r}
# 计算每列中值为0的比例
zero_percent <- apply(goal_gene_mt, 2, function(x) mean(x == 0))
# 判断是否超过整体 50% 的阈值
threshold <- 0.5
cols_to_keep <- which(zero_percent <= threshold)
cell_type<-cell[cols_to_keep,"Labels"]
cell_MR<-cell[cols_to_keep,"PR_or_MR"]
cols_to_MR<-which(cell$PR_or_MR=="Yes"&zero_percent <= threshold)
cols_to_PR<-which(cell$PR_or_MR=="No"&zero_percent <= threshold)
# 将剩余的列组合成新的数据框
new_mt <- goal_gene_mt[, cols_to_keep]
MR_mt<-goal_gene_mt[, cols_to_MR]
PR_mt<-goal_gene_mt[, cols_to_PR]
```

```{r}
# 进行计数
table(cell_MR)
```

```{r}
# 进行计数
hist(zero_percent)
```


```{r}
#保存筛选出来的总数据
# 导入所需的包
library(Matrix)
X<-as.data.frame(as.matrix(new_mt))
N<-dim(X)[1]
save(list=c("X", "N","cell_type"), file = "C:/Users/刘涛/Desktop/SIT/GSE137537/Realdata.RData")
```

```{r}
#保存筛选出来的MR数据
# 导入所需的包
library(Matrix)
X<-MR_mt
N<-dim(X)[2]
cell_label<-cell[cols_to_MR,"Labels"]
save(list=c("X", "N","cell_label"), file = "C:/Users/刘涛/Desktop/SIT/GSE137537/Code_and_data/RealApplication2/MRdata.RData")
```

```{r}
#保存筛选出来的PR数据
# 导入所需的包
library(Matrix)
X<-PR_mt
N<-dim(X)[2]
cell_label<-cell[cols_to_PR,"Labels"]
save(list=c("X", "N","cell_label"), file = "C:/Users/刘涛/Desktop/SIT/GSE137537/Code_and_data/RealApplication2/PRdata.RData")
```
# 倾向匹配得分
```{r}
library(MatchIt)
```
1.构建倾向匹配得分数据集
```{r}
#删除目标基因，只剩下非目标基因
rows_to_delete <- rownames(mt) %in% goal_gene
pro_MR_mt<-t(mt[!rows_to_delete,cols_to_MR])
pro_PR_mt<-t(mt[!rows_to_delete,cols_to_PR])
```
```{r}
#加上0和1以判别处理组和控制组
#创建一个全为零的列向量
new_column_MR <- rep(1, nrow(pro_MR_mt))
#将新列向量添加到矩阵中
pro_MR_mt <- cbind(pro_MR_mt, new_column_MR)
# 设置新列的列名为 "control"
colnames(pro_MR_mt)[ncol(pro_MR_mt)] <- "control"
```

```{r}
#加上0和1以判别处理组和控制组
#创建一个全为零的列向量
new_column_PR <- rep(0, nrow(pro_PR_mt))
#将新列向量添加到矩阵中
pro_PR_mt <- cbind(pro_PR_mt, new_column_PR)
# 设置新列的列名为 "control"
colnames(pro_PR_mt)[ncol(pro_PR_mt)] <- "control"
```

```{r}
#将两个矩阵合并
pro_mt<-rbind(pro_MR_mt,pro_PR_mt)
```
2.进行匹配得分
```{r}
# 导入所需的包
library(Matrix)
# 将 Matrix 对象转换为数据框
pro_mt_data <- as.data.frame(as.matrix(pro_mt),row.names = T)
```
```{r}
load("C:/Users/刘涛/Desktop/SIT/GSE137537/Code_and_data/RealApplication2/Pro_Data_result.RData")
load("C:/Users/刘涛/Desktop/SIT/GSE137537/goal_gene_mt.RData")
```


```{r}
# 获取不重复的列名
unique_columns <- unique(colnames(pro_mt_data))
pro_mt_data<-pro_mt_data[,unique_columns]
# 计算每列中值为0的比例
zero_percent <- apply(pro_mt_data, 2, function(x) mean(x == 0))
# 判断是否超过整体 50% 的阈值
threshold <- 0.5
cols_to_keep <- which(zero_percent <= threshold|(colnames(pro_mt_data)=="control"))
```

```{r}
# 得到匹配得分
fit1 <- glm(control ~ ., data = pro_mt_data[, cols_to_keep], family = binomial(link = "logit"))
fitted<-fit1$fitted.values
```
3.进行配对
```{r}
#导入分组数据
load("C:/Users/刘涛/Desktop/SIT/GSE137537/Code_and_data/RealApplication2/MRData_result.RData")
MR_group<-group_est
load("C:/Users/刘涛/Desktop/SIT/GSE137537/Code_and_data/RealApplication2/PRData_result.RData")
PR_group<-group_est+4
```
```{r}
#导入分组数据
pro_group<-rbind(MR_group,PR_group)
pro_group<-cbind(pro_group,fitted)
```

```{r}
#计算类与类间的距离
# 计算距离
distance_matrix <- dist(pro_group)
# 显示距离矩阵
print(distance_matrix)
front_four <- c(0.4498649, 0.4782220, 0.4691559, 0.7755977)
back_four <- c(0.6170101, 0.4738139, 0.4830212, 0.4345204)
# 使用solve_LSAP找到最优配对
solution <- solve_LSAP(distance_matrix)
# 打印配对结果
cat("配对结果:\n")
for (i in seq_along(solution)) {
  cat(sprintf("front_four[%d] (%f) <-> back_four[%d] (%f)\n",
              i, front_four[i], solution[i], back_four[solution[i]]))
}
#计算总距离
total_distance <- sum(distance_matrix[cbind(1:length(solution), solution)])
cat(sprintf("最小总距离: %f\n", total_distance))
```
