
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Switch to your path
knitr::opts_knit$set(root.dir = "F:/MMM-Bio/Data")
```

```{r Installation of databases such as clusterProfiler}

# Since clusterProfiler is not stored in CRAN, the `install` command is not usable.
# You must use BiocManager to install it.

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# Database for GO analysis
BiocManager::install("Seqinfo", version = "3.22", update = FALSE)
BiocManager::install("UCSC.utils", version = "3.22", update = FALSE)
BiocManager::install("GenomeInfoDb", version = "3.22", update = FALSE) # Depends on "Seqinfo," "UCSC.utils"
BiocManager::install("KEGGREST", update = FALSE)
BiocManager::install("AnnotationDbi", update = FALSE)
BiocManager::install(c("DOSE", "GO.db", "enrichplot"), update = FALSE)

BiocManager::install("clusterProfiler", update = FALSE) 
# Installation depends on the above packages


# Download the Human Genome Database
BiocManager::install("org.Hs.eg.db")

# Enrichment Analysis Plotting
BiocManager::install("GOplot")
BiocManager::install("enrichplot")

```


```{r Load software package}

library(stringr)
library(Seqinfo)
library(UCSC.utils) 
library(GenomeInfoDb)
library(clusterProfiler)
library(GOplot) # String Diagram, String Table Diagram, System Clustering Diagram
library(enrichplot)
library(ggplot2)

```


```{r Read gene SYMBOL}

# Set the gene_symbol reading path
gene_symbol <- read.csv("all.diffsig.csv")

```


```{r Convert SYMBOL to ENTREZID}

# Set as Human Genome Database
GO_database <- 'org.Hs.eg.db' 

# Begin converting SYMBOL to ENTREZID
gene <- bitr(gene_symbol$ID,fromType = 'SYMBOL',toType = 'ENTREZID',
             OrgDb = GO_database)

```


```{r GO Analysis}

GO <- enrichGO(gene$ENTREZID, #GO enrichment analysis
               OrgDb = GO_database,
               keyType = "ENTREZID",#Set the gene ID type to be read
               ont = "ALL",
                #(ont is set to ALL, thus including Biological Process, Cellular Component,Mollecular Function)
               pvalueCutoff = 0.05,#Set p-value threshold
               qvalueCutoff = 0.05,#Set Q-value threshold
               readable = T)


GO_BP <- enrichGO(gene$ENTREZID, 
               OrgDb = GO_database,
               keyType = "ENTREZID",
               ont = "BP",
               pvalueCutoff = 0.05,
               qvalueCutoff = 0.05,
               readable = T)

```


```{r Enriched Analysis Bubble Chart Complete}

# Ensuring vertical axis labels don't wrap is crucial—use scale_y_discrete
bubble_plot <- dotplot(GO, split = "ONTOLOGY") + 
               facet_grid(ONTOLOGY ~ ., scale = "free", space = 'fixed') +
               theme(axis.text.y = element_text(hjust = 1)) +
               scale_y_discrete(labels = function(x) str_wrap(x, width = 50) )
               # + theme(plot.margin = margin(0, 0, 0, 0))
bubble_plot

ggsave("bubble_all.pdf", plot = bubble_plot, width = 8, height = 10)

```


```{r Enrichment Analysis Bubble Chart: BP Section}

bubble_plot <- dotplot(GO_BP) +
               scale_y_discrete(labels = function(x) str_wrap(x, width = 50) ) 
               # + theme(plot.margin = margin(0, 0, 0, 0))
bubble_plot

ggsave("bubble_bp.pdf", plot = bubble_plot, width = 9, height = 3.8)

```



```{r Gene-Pathway Association Network Diagram}

# 基因-通路关联网络图 环状 左基因 右类别
circular_plot <- enrichplot::cnetplot(GO,circular=TRUE) 
                 # + theme(plot.margin = margin(0, 0, 0, 0))
circular_plot

ggsave("go_circular.pdf", plot = circular_plot, width = 7, height = 4.5)

```

```{r View the results of the GO analysis}

go_result <- GO@result

```


